-- 영화 테이블

DROP TABLE IF EXISTS MOVIE_TBL;
CREATE TABLE IF NOT EXISTS MOVIE_TBL(
		MOVIE_ID INT AUTO_INCREMENT PRIMARY KEY,
        MOVIE_TITLE VARCHAR(255) NOT NULL,
        MOVIE_RUN_TIME INT NOT NULL,
        MOVIE_TOTAL_SEATS INT NOT NULL,
        MOVIE_RESERVED_SEATS INT
)ENGINE = INNODB;

INSERT INTO MOVIE_TBL(

DROP TABLE IF EXISTS CINEMA_TBL;
CREATE TABLE IF NOT EXISTS CINEMA_TBL(
		CINEMA_ID INT AUTO_INCREMENT PRIMARY KEY,
        CINEMA_NAME VARCHAR(255) NOT NULL,
        CINEMA_LOCATION VARCHAR(255) NOT NULL
)ENGINE = INNODB;



DROP TABLE IF EXISTS RESERVATION_TBL;
CREATE TABLE IF NOT EXISTS RESERVATION_TBL(
		RESERVATION_NUM INT AUTO_INCREMENT PRIMARY KEY,
        USER_ID INT NOT NULL,
        RESERVED_TIME TIMESTAMP
)ENGINE = INNODB;
















        
		